config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  resources :articles
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'index#index'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'guide', to: 'guide#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence:true
  validates :contents, presence: true

  def self.getArticles(isMember = false)
    if (isMember)
      Article.all
    else
      Article.where(memberOnly: false)
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password validations: true
  validates :name, presence:true
  validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :current_user
  helper_method :signed_in?

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def sign_in(user)
    session[:user_id] = user.id
    @current_user = user
  end

  def sign_out
    @current_user = nil
    reset_session
  end

  def signed_in?
    @current_user.present?
  end

  private
    def require_sign_in!
      redirect_to login_path unless signed_in?
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :require_sign_in!, only: [:new, :create, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.getArticles(signed_in?)
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)
    @article.writer = @current_user.name
    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'News was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :contents, :memberOnly, :created_at, :updated_at)
    end
end

app/controllers/guide_controller.rb
class GuideController < ApplicationController

  def index

  end

end

app/controllers/index_controller.rb
class IndexController < ApplicationController

  def index
    @articles = Article.getArticles(signed_in?)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :set_user, only: [:create]

  skip_before_action :require_sign_in!, raise: false, only: [:new, :create]

  def new
  end

  def create
    if @user.authenticate(session_params[:password])
      sign_in(@user)
      redirect_to root_path
    else
      flash.now[:danger] = t('.flash.invalid_password')
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to login_path
  end

  def require_sign_in!
    require_sign_in!
  end

  private

    def set_user
      @user = User.find_by!(email: session_params[:email])
    rescue
      flash.now[:danger] = t('.flash.invalid_mail')
      render action: 'new'
    end

    # 許可するパラメータ
    def session_params
      params.require(:session).permit(:email, :password)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :created_at, :updated_at)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_form.html.erb
<%= form_with(model: article, local: true) do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :title %>
    <%= form.text_field :title, id: :article_title, class: "form-control"%>
  </div>

  <div class="field form-group">
    <%= form.label :contents %>
    <%= form.text_area :contents, id: :article_contents, class: "form-control"%>
  </div>

  <div class="field form-group">
    <%= form.label :memberOnly %>
    <%= form.check_box :memberOnly, id: :article_memberOnly, class: "form-control" %>
  </div>

  <div class="actions form-group">
    <%= form.submit :class=>"btn btn-primary"%>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Articles</h1>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Writer</th>
      <th>Contents</th>
      <th>Memberonly</th>
      <th>Created at</th>
      <th>Updated at</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.writer %></td>
        <td><%= article.contents %></td>
        <td><%= article.memberOnly %></td>
        <td><%= article.created_at %></td>
        <td><%= article.updated_at %></td>
        <td><%= link_to 'Show', article %></td>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Article', new_article_path %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<table class="table table-striped">
  <thead>
    <tr>
      <th><strong>Data Name</strong></th>
      <th><strong>Data</data></strong></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>Title</th>
      <td>
        <%= @article.title %>
      </td>
    </tr>
    <tr>
      <th>Writer</th>
      <td>
        <%= @article.writer %>
      </td>
    </tr>
    <tr>
      <th>Contents</th>
      <td>
        <%= @article.contents %>
      </td>
    </tr>
    <tr>
      <th>MemberOnly</th>
      <td>
        <%= @article.memberOnly %>
      </td>
    </tr>
    <tr>
      <th>Created at</th>
      <td>
        <%= @article.created_at %>
      </td>
    </tr>
  </tbody>
</table>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/index/index.html.erb
<nav class="navbar navbar-default">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbarEexample6">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
  </div>
  <div class="collapse navbar-collapse" id="navbarEexample6">
    <ul class="nav navbar-nav">
      <li><%= link_to 'Article', articles_path %></li>
      <li><%= link_to 'User', users_path %></li>
    </ul>
  </div>
</nav>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Writer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.writer %></td>
        <td><%= link_to 'Show', article %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogExample</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css" rel="stylesheet">
    <link href="chrome-extension://febilkbfcbhebfnokafefeacimjdckgl/theme/Github.css" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"></script>

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body style="width:1100px;">
    <div class="header" style="border-bottom:solid 1px #ccc; margin-bottom:10px; padding-bottom:10px;">
      <h1>Blog-example</h1>
      <% if @current_user %>
        <p style="text-align:right;"><%= @current_user.name %> | <%= link_to 'ログアウト', logout_path, method: :delete %></p>
      <% else %>
        <p style="text-align:right;"><%= link_to 'ログイン', login_path %></p>
      <% end %>
    </div>
    <%= yield %>
    <div class="footer" style="border-top:solid 1px #ccc; margin-top:10px; padding-top:10px;">
      <%= link_to 'TOP', root_path %>
    </div>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :name %>
    <%= form.text_field :name, id: :user_name, class: "form-control"  %>
  </div>

  <div class="field form-group">
    <%= form.label :email %>
    <%= form.text_field :email, id: :user_email, class: "form-control"  %>
  </div>

  <div class="field form-group">
    <%= form.label :password %>
    <%= form.text_field :password, id: :user_password, class: "form-control"  %>
  </div>

  <div class="actions">
    <%= form.submit class:"btn btn-primary"%>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Password digest</th>
      <th>Created at</th>
      <th>Updated at</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.password_digest %></td>
        <td><%= user.created_at %></td>
        <td><%= user.updated_at %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<table class="table table-striped">
  <thead>
    <tr>
      <th><strong>Data Name</strong></th>
      <th><strong>Data</data></strong></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>Name</th>
      <td>
        <%= @user.name %>
      </td>
    </tr>
    <tr>
      <th>Email</th>
      <td>
        <%= @user.email %>
      </td>
    </tr>
    <tr>
      <th>Password digest</th>
      <td>
        <%= @user.password_digest %>
      </td>
    </tr>
    <tr>
      <th>Created at</th>
      <td>
        <%= @user.created_at %>
      </td>
    </tr>
  </tbody>
</table>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>